apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon-set
spec:
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
